.PHONY: all clean pwd ls head tail mkdir rmdir find yacc

all: pwd ls head tail mkdir rmdir find yacc

pwd:
	cd pwd && $(MAKE) all

ls:
	cd ls && $(MAKE) all

head:
	cd head && $(MAKE) all

tail:
	cd tail && $(MAKE) all

mkdir:
	cd mkdir && $(MAKE) all

rmdir:
	cd rmdir && $(MAKE) all

find:
	cd find && $(MAKE) all

yacc:
	cd yacc && $(MAKE) all

clean:
	cd pwd && $(MAKE) clean
	cd ls && $(MAKE) clean
	cd head && $(MAKE) clean
	cd tail && $(MAKE) clean
	cd mkdir && $(MAKE) clean
	cd rmdir && $(MAKE) clean
	cd find && $(MAKE) clean
	cd yacc && $(MAKE) clean